version: "3.8"
services:
  project-service:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL_PROJECT}
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      - dev-db
    networks:
      - app-network

  notification-service:
    build:
      context: ./notification-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
